### ISSUE TITLE
Script that fetch data from excel and save as json

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#97] opened 2019-03-12 13:33 UTC
We need to parse all data from excel and save them in a json format that follows our db format, so we can import all old timeregs as json into our firestore.

**Comment by astyltsvig** [comment] 2019-03-20 09:41
Its possible to export data as csv from excel, and then parse them into json. Probably it is how we should solve this issue

**Comment by cph-lh** [comment] 2019-03-29 09:55
Duplicate of #186 - closing this.

**Closed as completed by cph-lh** 2019-03-29 09:55 UTC
Labels: Prio 2 - should have, Status - duplicate
